### 机器学习开始

##### 机器学习流程
* 获取数据
* 数据处理
* 特征工程
* 机器学习模型算法训练
* 模型评估
* 应用

1. scikit-learn数据集API介绍
加载数据集：
    datasets.load_*()
        -获取小规模数据集，数据包含在datasets里面
    datasets.fetch_*(data_home = None,subset = 'train')
        -获取大规模数据集，需要从网络上下载，data_home参数表示数据集下载的目录，默认~/scikit_learn_data/
        -第二个参数表示需要加载的数据集，有训练集和测试集,也可以用'all'表示都要
数据集的返回值
    datasets.base.Bunch()返回值继承自字典类型，有五个键:
        data:特征数据数组，是二维的numpy.ndarray数组
        target:标签数组
        DESCR:数据描述
        featrue_names:特征名
        target_names:标签名

In [1]:
from sklearn.datasets import load_iris

def datasets_demo():
    #sklean数据集的使用
    iris = load_iris()
    print("鸢尾花数据集:\n",iris["DESCR"])
    return None
datasets_demo()

鸢尾花数据集:
 Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values

2. 数据集划分api:
    sklearn.model_selection.train_test_split(arrays,*options)
        x数据集的特征值
        y数据集的标签值
        test_size:测试集的大小，用float浮点数。如需测试百分之二十的数据，则传入0.2
        randmo_state随机数种子：不同的种子造成不同的采样结果
        return 训练集特征值，测试集特征值，训练集目标值，测试集目标值(注意返回结果的顺序)

In [5]:
from sklearn.model_selection import train_test_split

def ds_demo2():
    iris = load_iris()
    x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size = 0.2,random_state = 22)
    print("训练集的特征值：\n" ,x_train,x_train.shape)#shape是指返回的二维数组的行和列
ds_demo2()

训练集的特征值：
 [[4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [5.7 2.8 4.5 1.3]
 [5.  3.4 1.6 0.4]
 [5.1 3.4 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [6.9 3.1 5.4 2.1]
 [6.7 2.5 5.8 1.8]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 4.7 1.6]
 [5.4 3.9 1.3 0.4]
 [4.4 3.2 1.3 0.2]
 [6.7 3.  5.  1.7]
 [5.6 3.  4.1 1.3]
 [5.7 2.5 5.  2. ]
 [6.5 3.  5.8 2.2]
 [5.  3.6 1.4 0.2]
 [6.1 2.8 4.  1.3]
 [6.  3.4 4.5 1.6]
 [6.7 3.  5.2 2.3]
 [5.7 4.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.  3.5 1.3 0.3]
 [4.8 3.  1.4 0.1]
 [5.5 4.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [7.2 3.2 6.  1.8]
 [5.1 2.5 3.  1.1]
 [6.4 3.2 4.5 1.5]
 [7.3 2.9 6.3 1.8]
 [4.5 2.3 1.3 0.3]
 [5.  3.  1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [5.  3.3 1.4 0.2]
 [6.2 2.2 4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [6.4 2.9 4.3 1.3]
 [4.9 2.4 3.3 1. ]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [5.9 3.2 4.8 1.8]
 [5.4 3.9 1.7 0.4]
 [6.  2.2 4.  1. ]
 [6.4 2.8 5.6 2.1]
 [4.8 3.4 1.9 0.2]
 [6.4 3.1 5.5 1.8]
 [5.9 3.  4.2 1.5]
 [6.5 3.  5.5 1.8]
 [6.  2.9 4.5 1.5]
 [5.5 2.4 3.8 1.1]
 [

##### 特征工程介绍
> 数据和特征决定了机器学习的上限,而模型和算法只是逼近这个上限而已

###### 包含内容
1. 特征抽取
2. 特征预处理
3. 特征降维

##### 1. 特征提取：将文本、图像等转换成及其学习能够处理得数字特征
特征提取api : sklearn.feature_extraction()

###### 2. 字典特征提取 - 类别 -> one-hot编码
sklearn.feature_extraction.DicVectorize(sparse = True...)
    - DicVectorize.fit_transform(X) X：字典或包含了字典的迭代器;返回一个sparse矩阵(稀疏矩阵)

In [11]:
from sklearn.feature_extraction import DictVectorizer
def ds_demo3():
    data = [{'city': 'guangzhou','temp':100},{'city':'shanghai','temp': 60},{'city':'shenzhen','temp':40}]
    #1.实例化一个转换器类
    transfer = DictVectorizer(sparse = False)#默认返回一个稀疏矩阵，为了节省内存
    #2.调用transform方法
    data_new = transfer.fit_transform(data)
    print("data_new:\n",data_new)
    print("特征名字:\n", transfer.get_feature_names())#符合特征的那一行在data_new中所在列是1，否则为0
    return None
ds_demo3()

data_new:
 [[  1.   0.   0. 100.]
 [  0.   1.   0.  60.]
 [  0.   0.   1.  40.]]
特征名字:
 ['city=guangzhou', 'city=shanghai', 'city=shenzhen', 'temp']


###### 3.文本特征提取
sklearn.feature_extraction.text.CounterVectorizer(stop_words = [])
    - stop_words为停用词表，将不需要统计的词放入列表中传进去
    - 返回词频矩阵

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
def count():
    words = ["life is too long,life is too short","i like python,i dislike python"]
    transfer = CountVectorizer(stop_words = ['is','too'])
    data = transfer.fit_transform(words)
    print("特征值为：\n" ,data.toarray())#将稀疏矩阵转为普通矩阵
    print("特征名字:\n",transfer.get_feature_names())
count()

特征值为：
 [[0 2 0 1 0 1]
 [1 0 1 0 2 0]]
特征名字:
 ['dislike', 'life', 'like', 'long', 'python', 'short']


中文文本的特征提取

In [30]:
import jieba

#写一个进行分词的函数
def cut_word(text):
    a = " ".join(list(jieba.cut(text)))#进行一次强转
    #print(a)
    return a
def chinese():
    data = ["重生的力量来自真我","战胜可敬的对手耶一耶","坚持信念是我的所有"]
    data_new = []
    for string in data:
        data_new.append(cut_word(string))
    transfer = CountVectorizer()
    output = transfer.fit_transform(data_new)
    print("特征值为：\n" ,output.toarray())#将稀疏矩阵转为普通矩阵
    print("特征名字:\n",transfer.get_feature_names())
chinese()

特征值为：
 [[0 1 0 0 0 0 0 1 0 1]
 [0 0 1 0 1 1 0 0 1 0]
 [1 0 0 1 0 0 1 0 0 0]]
特征名字:
 ['信念', '力量', '可敬', '坚持', '对手', '战胜', '所有', '来自', '耶一耶', '重生']


- 关键词：一些词在一篇文章中经常出现，在另一篇文章很少出现，则称为关键词。由此实现对于文章的分类。
TF-IDF作用：衡量一个词在一篇文章中的重要程度
        TF:即一个词在文章中的词频
        IDF：逆向文档频率，是一个词语的普遍重要性的衡量。词用得越普遍，idf值越小。
   TF-IDF值 = tf * idf
   
sklearn.feature_extraction.text.TfidfVectorizer(X)
    - X：文本或包含文本的可迭代对象
    - 返回词的权重矩阵

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

def tfidf():
    transfer = TfidfVectorizer()
    data = ["这个月的经济总量一直呈现低迷态势，为此政府一直在努力发展经济，争取提高经济水平","我真的非常生气，非常生气，非常生气"]
    cdata = []
    for string in data:
        cdata.append(cut_word(string))
    data_new = transfer.fit_transform(cdata)
    print(data_new.toarray())
    print(transfer.get_feature_names())
tfidf()

[[0.4472136  0.2236068  0.2236068  0.2236068  0.2236068  0.2236068
  0.2236068  0.2236068  0.2236068  0.2236068  0.2236068  0.
  0.         0.4472136  0.2236068  0.2236068  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.6882472
  0.22941573 0.         0.         0.         0.6882472 ]]
['一直', '为此', '争取', '低迷', '努力', '发展', '呈现', '态势', '提高', '政府', '水平', '生气', '真的', '经济', '经济总量', '这个', '非常']


#### 特征预处理
通过一些转换函数将特征数据转换为更加适合算法模型的特征数据，将不同规格的数据转换到同一规格
1. 包含内容:
    归一化
    标准化
2. 预处理api
    sklearn.preprocessing.MinMaxScaler(feature_range = (0,1))
    MinMaxScaler(X)
        X:numpy.array 格式:(样本的大小(行数),样本的特征(列数))
        return 转换后的numpy.array

归一化处理

In [38]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

def MinMax():
    data = pd.read_csv("dating.txt")
    tran = MinMaxScaler(feature_range = (2,3))
    newdata = tran.fit_transform(data)
    print(newdata)
MinMax()

[[2.         2.         2.         3.        ]
 [2.8309057  2.34375    2.03225806 2.        ]
 [3.         3.         3.         2.90909091]]


##### 由于归一化受最大值和最小值影响较大，数据容易失真，因此还有标准化处理:
x = (x0 - 平均值) / 标准差
sklearn.preprocessing.StandaredScaler

#### 特征降维
降低随机变量的维度，得到一组不相关的主变量的过程

1. 特征选择  
    Filter过滤式  
        方差过滤法：低方差特征过滤  
        相关系数  
    Embeded嵌入式 
        决策树  
        正则化  
        深度学习  

1.1 低方差过滤

sklearn.feature.selection.VarianceThreshold(threshold = 0.0)  
    - 将方差低于threshold的特征删除

##### 相关系数的计算
$$ r = \frac{n\sum_{}^{}{xy} - \sum_{}^{}{x}\sum_{}^{}{y}}{\sqrt{n\sum_{}^{}{x^2}-(\sum_{}^{}{x})^2}\sqrt{n\sum_{}^{}{y^2}-(\sum_{}^{}{y})^2}} $$  
r > 0为正相关，r < 0为负相关  
|r|越大，相关性越大

当特征与特征之间相关性很高时：  
    1. 选取其中一个  
    2. 加权求和  
    3. 主成分分析

##### 主成分分析 
在降维的过程中，可能会舍弃原有数据，创造新的变量  
##### API
* sklearn.decomposition.PCA(n_components = None)  
    n_components:  
        -小数 ：表示保留百分之多少的信息  
        -整数 ：减少到多少特征  
   PCA.fit_transform(X)

In [41]:
from sklearn.decomposition import PCA
def pca():
    data = [[2,8,4,5],[6,3,0,8],[5,4,9,1]]
    transfer = PCA(n_components = 2)#将4个特征降为两个特征
    data_new = transfer.fit_transform(data);
    print(data_new)
pca()

[[ 1.22879107e-15  3.82970843e+00]
 [ 5.74456265e+00 -1.91485422e+00]
 [-5.74456265e+00 -1.91485422e+00]]


#### 案例 ：探究用户对物品类别的喜好细分降维
* 找到用户user_id和物品aisle之间的联系
    1. 将user_id和aisle放在一张表中 - 合并
    2. 找到两者之间的关系 - 交叉表和透视表
    3. 特征冗余过多，要进行降维

因数据不足，暂时跳过